replicaCount: 1
image:
  repository: ""
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
serviceAccount:
  create: false
autoscaling:
  enabled: false
ingress:
  enabled: false
env: