kind: Namespace
apiVersion: v1
metadata:
  name: logging
  labels:
    name: logging
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: logging
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  project: elasticsearch
  source:
    repoURL: https://github.com/elastic/helm-charts.git
    targetRevision: v8.5.1
    path: ./elasticsearch
    helm:
      values: |
        minimumMasterNodes: 1
        replicas: 1
        resources:
          requests:
            cpu: 0
            memory: 0
