kind: Namespace
apiVersion: v1
metadata:
  name: loki
  labels:
    name: loki
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: loki
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: loki
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  project: loki
  source:
    repoURL: https://github.com/bitnami/charts.git
    targetRevision: main
    path: ./bitnami/grafana-loki
