kind: Namespace
apiVersion: v1
metadata:
  name: prometheus
  labels:
    name: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: prometheus
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: prometheus
  source:
    repoURL: https://github.com/bitnami/charts.git
    targetRevision: main
    path: ./bitnami/kube-prometheus
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
