replicaCount: 4
image:
  repository: ""
  tag: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 3000
serviceAccount:
  create: false
autoscaling:
  enabled: false
ingress:
  enabled: false
env:
podAnnotations: